#!/usr/bin/bash
source helpers

first_node=$1
node=$2

echoci -c blue -d "Installing master node $node"

scp control-plane-config.yaml $node:
ssh $node 'sudo mkdir -p /etc/rancher/k3s; sudo cp control-plane-config.yaml /etc/rancher/k3s/config.yaml'

[ "$first_node" = "$node" ] || {
    cluster_detail="K3S_URL=https://$first_node:6443 K3S_TOKEN='$(ssh $first_node sudo cat /var/lib/rancher/k3s/server/node-token)'"
}

ssh $node "curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL=latest INSTALL_K3S_EXEC='server' $cluster_detail sh -"
