#!/bin/bash

agent_nodes=("elendil" "aragorn" "isildur" "faramir" "boromir" "cmdrcody" "elrond")
master_nodes=("samwise" "meriadoc" "frodo")

for node in "${agent_nodes[@]}"; do
    echo $node:
    ssh $node 'if [ -e /usr/local/bin/k3s-agent-uninstall.sh ]; then sudo /usr/local/bin/k3s-agent-uninstall.sh; sudo reboot; else echo "no k3s uninstall"; fi'
done

# for node in "${master_nodes[@]}"; do
#     echo $node:
#     ssh $node 'if [ -e /usr/local/bin/k3s-uninstall.sh ]; then sudo /usr/local/bin/k3s-uninstall.sh; else echo "no k3s uninstall"; fi'
# done

# for node in "${master_nodes[@]}"; do ssh $node 'sudo reboot'; done
