#!/bin/bash

# create or update the loki namespace so this script is idempotent
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Namespace
metadata:
  name: loki
EOF

# create or update the loki helm installation
helm upgrade --install loki grafana/loki -n loki \
    --set "loki.storage.type=s3" \
    --set "loki.storage.s3.s3=loki-storage" \
    --set "loki.storage.s3.region=eastus" \
    --set "loki.storage.s3.endpoint=https://minio.loki.svc.cluster.local:443" \
    --set "loki.storage.s3.secretAccessKey="$(get-secret minio-secretKey) \
    --set "loki.storage.s3.accessKeyId=$(get-secret minio-accessKey)"