# deploy this to the cluster to trigger the creation of a TLS certificate from Letsencrypt
# this isn't part of the full build because we rebuild too often - we don't want to hit the rate limit
# Once we have valid certificate we can save it and reuse till it expires
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: splat-g2dev-net-certificate
  namespace: ingress-nginx
spec:
  secretName: splat-g2dev-net-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "*.g2dev.net"
  dnsNames:
  - "*.g2dev.net"
