apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: minas-tirith
  namespace: cnpg-system
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised

  storage:
    size: 10Gi
