apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: minas-tirith
  namespace: cnpg-system
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised

  superuserSecret:
    name: superuser-secret
  enableSuperuserAccess: true

  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: app-secret

  storage:
    size: 10Gi
